# Generated by Django 3.0.7 on 2020-07-05 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktodo',
            name='user',
            field=models.ForeignKey(default=4431420032, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
